##========---
##=- VALET
##=====---
# Vapour Technology All-Purpose Library
# Copyright 2001 Vapour Technology Ltd.
#
# Add confidentiality notice

# NOTE: Will eventually be generated by VMake

# 23/09/2001 - Warren Moore
# $Id: base.mk,v 1.1 2001/10/17 00:24:00 vap-warren Exp $

# common defines
VALET_INC = ../include
VALET_LIB = ../lib

##===--- noarch
MAKE = make
CC = gcc
CXX = g++
CFLAGS = -g -O -Wall -I$(VALET_INC)
CXXFLAGS = 
AR = ar
ARFLAGS = rcs
RANLIB = ranlib
LD = ld
LDFLAGS = -L$(VALET_LIB)

##===--- dc
KOS_ARCH_DIR = $(KOS_BASE)/kernel/arch/$(KOS_ARCH)
KOS_START = $(KOS_ARCH_DIR)/kernel/startup.o

#CC = $(KOS_CC)
#CXX = $(KOS_CCPLUS)
#CFLAGS = $(KOS_CFLAGS) -D_arch_$(KOS_ARCH) -I$(VALET_INC) -I$(KOS_INCS) -I$(KOS_BASE)/kernel/arch/$(KOS_ARCH)/include
#CXXFLAGS = $(KOS_CPPFLAGS)
#AR = $(KOS_AR)
#ARFLAGS = rcs
#RANLIB = /usr/local/dc/sh-elf/bin/sh-elf-ranlib
#LD = $(KOS_LD)
#LDFLAGS = $(KOS_LDFLAGS) -L$(VALET_LIB) $(KOS_START) -L$(KOS_BASE)/lib

.PHONY: all build test clean distclean

# Targets

all: build

$(LIB): $(OBJS)
	$(RANLIB) $(LIB)

# Production rules
	
.cpp.o:
	$(CXX) $(CFLAGS) $(CXXFLAGS) -c $<

.cpp.a:
	$(CXX) $(CFLAGS) $(CXXFLAGS) -c $<
	$(AR) $(ARFLAGS) $@ $%

# Default

.DEFAULT:
	@echo Unknown target: $@

